---
- name: Setup nginx for drone
  hosts: app
  become: true
  become_user: root
  gather_facts: False
  vars_files:
    - "vars/main.yml"
  roles:
    - { role: nginx }
  tasks:
    - name: copy nginx virtual host file
      template: src="templates/nginx-config.j2"
                dest="/etc/nginx/sites-available/01_pa"
                owner=root
                group=root

    - name: link nginx virtual host file
      file: src="/etc/nginx/sites-available/01_pa"
            dest="/etc/nginx/sites-enabled/01_pa"
            state=link

    - name: restart nginx
      service: name=nginx state=restarted
